### ISSUE TITLE
تشغيل البرنامج مع بدء الويندوز 

### ISSUE THREAD

**Issue by MesterPerfect** [rn0x/Altaqwaa-Islamic-Desktop-Application#1]
السَلام عليكم ورحمة الله وبركاته 
يريت أخي لو تضيف أمكانية تشغيل البرنامج مع بدء تشغيل الويندوز بحيث يتم تشغيل البرنامج مع تشغيل الويندوز ولكن دون ظهور نافذة بل يكون في منطقة الإشعارات بالأسفل

**Comment by rn0x** [comment]
https://github.com/rn0x/Altaqwaa-Islamic-Desktop-Application/commit/a7712d9f555201d2cc992bec58c178b496b50e34

**Comment by rn0x** [comment]
a7712d9f555201d2cc992bec58c178b496b50e34

وعليكم السلام ورحمة الله وبركاته 
تم

# [v1.0.5](https://github.com/rn0x/Altaqwaa-Islamic-Desktop-Application/releases/edit/v1.0.5)
تشغيل التطبيق في الخلفية مع بدء تشغيل النظام ✔️

**Comment by rn0x** [comment]
#a7712d9f555201d2cc992bec58c178b496b50e34

**Comment by MesterPerfect** [comment]
شكرا لك 
ستتم التجربة
