### ISSUE TITLE
السلام عليكم 

### ISSUE THREAD

**Issue by fahad4x4** [rn0x/Altaqwaa-Islamic-Desktop-Application#10]
بارك الله فيك اخي الكريم وجزاك الله عنا كل خير.
لدي طلب اذا ممكن ان تحول هذا العمل الرائع الى اضافة لـ ووردبريس.

**Comment by rn0x** [comment]
> بارك الله فيك اخي الكريم وجزاك الله عنا كل خير. لدي طلب اذا ممكن ان تحول هذا العمل الرائع الى اضافة لـ ووردبريس.

وفيك بارك الله, مافهمت عليك كيف تبي احول تطبيق سطح مكتب الى إضافة ووردبريس ؟



> السلام عليكم ورحمة الله وبركاته جزاك الله خيرا لدى استفسار لماذا غير متاح تغير المنطقة الزمنية
> 
> ![2023-01-12_17-41](https://user-images.githubusercontent.com/19464723/212114762-328b9033-3c1b-4cff-a5af-ccbc81b5e1d1.png)

وعليكم السلام ورحمة الله وبركاته 
آمين وإياك 
متاح فقط قم بكتابة المنطقة الزمنية ثم اضغط على حفظ 

المناطق الزمنية مثل 
مصر = Africa/Cairo
السعودية = Asia/Riyadh

لمعرفة منطقتك الزمنية قم بالبحث عنها في الرابط التالي 

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by KhaledxMohamed1955** [comment]
جزاك الله عنا خير الجزاء أخى

**Comment by rn0x** [comment]
> جزاك الله عنا خير الجزاء أخى


آمين ومن يقول 💐
