### ISSUE TITLE
التطبيق لا يعمل بشكل صحيح على واجهة جنوم على لنكس

### ISSUE THREAD

**Issue by MehdiLgithub** [rn0x/Altaqwaa-Islamic-Desktop-Application#17]
![Screenshot from 2023-03-11 17-53-15](https://user-images.githubusercontent.com/53827305/224497171-d3f2a03e-7d08-4e69-8970-5e3d9dc8b860.png)

عند تصغير نافذة التطبيق على جنوم تختفي الواجهة كليا دون توقف التطبيق حيث يستمر في تلوة القران رغم عدم توفر اي واجهة 
فلا يمكن إقافه و عند إعادة فتحه يتم إطلاق نسخة جديدة من التطبيق
 
[Screencast from 2023-03-11 17-57-55.webm](https://user-images.githubusercontent.com/53827305/224499270-5524ff07-fbd8-495e-aeca-cb252dd00003.webm)

**Comment by kemzops** [comment]
السلام عليكم اخي... التطبيق لما ينعمل له minimize (تصغير) يصبح في وضع مخفي ولكنه شغال في الخلفية ولأن جنوم بطبيعته مافيه **App Indicator** 
ف ما هيظهر في الـ panel

الحل: حاليا مافي خيار في التطبيق لإلغاء هذه الميزة ولكن بأذن الله بالإصدارات القادمة سوف أحرص على إضافتها... حاليا الحل المؤقت استخدام اضافة (اكستنشن) لجنوم مثل:

https://extensions.gnome.org/extension/615/appindicator-support/?ref=its-foss
الي بتقوم بعمل App Indicator في الـ Panel الخاصة بك

صورة للتوضيح عن عمل الإضافة :
![image](https://user-images.githubusercontent.com/52936496/224504976-a9c830bb-e09f-45d2-b9a6-de7f47a67949.png)

**Comment by kemzops** [comment]
@MehdiLgithub بإنتظار ردك لو أنحلت المشكلة...

**Comment by MehdiLgithub** [comment]
و عليكم السلام شكرا على الرد السريع 

اجل قمت بتثبيت الإضافة و التطبيق يعمل بشكل جيد 
و ما دمت ستضيف خاصية التصغير للبانل في الإصدار القادم يمكنك إغلاق المشكلة

**Comment by kemzops** [comment]
تمام شكرا لك على الذكير بالمشكلة... لايمكن تجربة التطبيق على كل الواجهات والأنظمة والتوزيعات.
