### ISSUE TITLE
طلب خاص

### ISSUE THREAD

**Issue by Turkidev** [rn0x/Altaqwaa-Islamic-Desktop-Application#19]
السلام عليكم 
الرجاء من اصحاب البرنامج التواصل معي على الدسكورد لتقديم عرض
Turki#1234

**Comment by kemzops** [comment]
حياك الله ونشكر جهودك... ولكن الهدف حاليا تطبيق الأندرويد... وصلت رسالتك... يعطيك العافية وفرصة سعيدة.
