### ISSUE TITLE
أذكار عشوائية 

### ISSUE THREAD

**Issue by MesterPerfect** [rn0x/Altaqwaa-Islamic-Desktop-Application#2]
السَلام عليكم ورحمة الله وبركاته 
هذا اقتراح ثاني بإذن الله يكون سهل التنفيذ 
يريت لو يتم إضافة ميزة لتشغيل الإذكار العشوائية 
بمعنا, كل 5 دقائق أو 10 دقائق يقوم بعرض ذِكر بشكل عشوائي ويمكن استخدام أذكار صوتية إن أمكن 
إذا كان هناك صعوبة في عرض نافذة صغيرة تحتوي على ذِكر عشوائي من الإذكار التي ستكون مرفقة في البرنامج 
فيمكن إرسال الذكر عبر إشعارات الويندوز كما في حالة التنبيه بوقت الصلاه
تحياتي

**Comment by rn0x** [comment]
وعليكم السلام ورحمة الله وبركاته 

1edc07b9314197ae0b2b07abcd322834737c0f39
0971caee37d9bc818bd1f0bd10d0e3e9c35ef2ec
f04ccfd08c6f85d1b4b87a2b76116795a2fa3eb1

[أبرز التعديلات في الإصدار v1.0.6](https://github.com/rn0x/Altaqwaa-Islamic-Desktop-Application/releases/tag/v1.0.6)

- إضافة إشعارات أذكار
- أذكار الصباح والمساء صوت
- إضافة خيارات إيقاف وتفعيل الإشعارات


<p align="center">
    <img align="center" src="https://raw.githubusercontent.com/rn0x/Altaqwaa-Islamic-Desktop-Application/main/github/v1.0.6.png">
</p>
