### ISSUE TITLE
Flathub

### ISSUE THREAD

**Issue by RasheedAZ** [rn0x/Altaqwaa-Islamic-Desktop-Application#23]
جزاكم الله خيرا على الجهد المبذول في تطوير هذا البرنامج المفيد الرائع. هل يمكم توفيره على
flathub؟

**Comment by kemzops** [comment]
شكرا لك من جديد 😅... بالفعل الهدف الحالي هو رفعه على `flathub` ولكن تواجهنا بعض الصعوبات بسب عدم "وضوح" الطريقة الرسمية لرفع التطبيقات... ولكن بأذن الله سنحاول... ونحن بلفعل ندعم حزم `flatpak`.

**Comment by o-kotb** [comment]
هو ازاي بالظبت بتبنو ال flatpak؟ المفروض نفس ال manifest البتبني بيها ترفعها زي كده https://github.com/flathub/flathub/wiki/App-Submission

على العموم ، طريقة بني تطبيقات flatpak electron اصعب شوية من العادي ومحتاجة base app زي كده https://docs.flatpak.org/en/latest/electron.html (الارشادات هنا قديمة وفيها اخطاء)

[انا بحاول اعمل وحدة](https://github.com/o-kotb/org.altaqwaa.Altaqwaa) لاكن لسه موصلتش لحاجة. ممكن هكمل بكرة.

**Comment by kemzops** [comment]
بوركت الجهود... المشكلة بصراحة عدم توفر وقت انا مشغول بالحياة والدراسة وريان كذلك... ومشغولين بتطبيق الأندرويد... اذا أمكن صيانة ومتابعة مستودع `flathub` جزاك الله خير.

**Comment by o-kotb** [comment]
اسف على التاخير. كان عندي امتحانات.

[أنا عملت ال manifest](https://github.com/o-kotb/flathub/tree/org.altaqwaa.Altaqwaa) لاكن اتباعا لنصايح (أو عدم) مطوري Flatpak ، أنا خلتها تستعمل الحزم من github releases بدل بنيها (الكل بيكره electron هناك ¯\_(ツ)_/¯ ) انا برضو عملت ملف metainfo جديد بالمعلومات المتاحة لي عشان مكنش موجود في المشروع.

قبل منرفعها ، المفروض تغيرو ال app id الحالي. لازم يتبع مواصفات Freedesktop. مثلا tld.name.app. يبدو ان الاسم `altaqwaa.org` تبعكم فانا شايف `org.altaqwaa.Altaqwaa` هيكون مناسب لاكن `me.rn0x.Altaqwaa` هينفع برضو.

اخر حاجة هي تضمن `package-lock.json` جوة المستودع. ده ملوش علاقة بflatpak بل عشان يسهل بني البرنامج لأي حد محتاج إصدار كل حزمة https://stackoverflow.com/a/48524475

لو شايفين كل حاجة كويسة ، هفتح pull request لFlathub

**Comment by kemzops** [comment]
حابب اشكرك على المساهمة بالمشروع وشكرا الك على توضيح بعض الأمور... بالنسبة لـمواصفات Freedesktop الأسم بالفعل جاهز وهو `org.altaqwaa.rn0x` ولكن اظن هنغيره لـ `org.altaqwaa.Altaqwaa` ولكن اظن ينفع حاليا ؟.

وبالنسبة لـ `package-lock.json` ممكن للمشاريع الي تستخدم بكجات ضخمة وبكون عددها كبير ولكن بالنسبة للتقوى كل التبعيات الخاصة بالمشروع بسيطة ومكشوفة وما نستخدم أي مكاتب ممكن تسبب مشاكل غير `Electron` والي بصراحة بحصله تحديثات بشكل مستمر وتصليحات ما نبي نثبت على اصدار معين حاليا... ف مثلاا الاصدار الأخير من التطبيق نزل بعده تحديثين اصلاحات في اقل من شهر. فنحن ثابتين عنفس الاصدار الـ `Major` وبنحدث الـ `Minor` والـ `Patches`.

وياريت لو تقدر تتواصل معاي بشكل مباشر بكون أفضل.

**Comment by o-kotb** [comment]
> بالنسبة لـمواصفات Freedesktop الأسم بالفعل جاهز وهو org.altaqwaa.rn0x ولكن اظن هنغيره لـ org.altaqwaa.Altaqwaa ولكن اظن ينفع حاليا ؟.

هي المشكلة في الاسم الحالي انه معمول `com.example.author` المفروض يتبع Reverse DNS زي `com.example.app` حتى لو التطبيق نفس اسم الموقع.
https://docs.flatpak.org/en/latest/conventions.html#application-ids
https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names

> وياريت لو تقدر تتواصل معاي بشكل مباشر بكون أفضل.

ممكن تبعتلي ايميل `omar@omarkotb.com`
أو رسائل فورية على ماتركس

`@omark:fedora.im`

**Comment by o-kotb** [comment]
ممكن نقفل ده خلاص :)

https://flathub.org/apps/details/org.altaqwaa.Altaqwaa

**Comment by o-kotb** [comment]
الماسك [altaqwaa.org](https://altaqwaa.org) ، حطو الـtoken ديه `a306fc1f-34ab-4ed3-b526-34bfdc614588` في https://altaqwaa.org/.well-known/org.flathub.VerifiedApps.txt عشان يبأة verified

![Screenshot_20230402_115053](https://user-images.githubusercontent.com/72304125/229345635-664c5b3e-9b1e-460a-ac80-7694b73bc475.png)

**Comment by kemzops** [comment]
تمام المفروض كذا كلشيء تمام سويت merge للصفحة @o-kotb... هقفل.

**Comment by o-kotb** [comment]
التطبيق دلوقتي verified على Flathub :D

https://beta.flathub.org/apps/org.altaqwaa.Altaqwaa
