### ISSUE TITLE
the voice is not working 

### ISSUE THREAD

**Issue by zeyadelkholyttt** [rn0x/Altaqwaa-Islamic-Desktop-Application#24]
# info
wm: dwm
distro: void musl **with dualboot**
gpu: amd
cpu: intel
download method : flatpak
 # error
`#32 0x55d74d42a1cc <unknown>
#33 0x55d74d3ecfc8 <unknown>
#34 0x55d74cd3f273 <unknown>
#35 0x55d74a394a17 <unknown>
#36 0x55d74a39585b <unknown>
#37 0x55d74a3929b2 <unknown>
#38 0x55d74a3930e5 <unknown>
#39 0x55d74a0df55d <unknown>
#40 0x7f0d5d6df072 __libc_start_main
ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

[184:0327/181201.574089:ERROR:alsa_util.cc(204)] PcmOpen: plug:default,Connection refused
^C
`

**Comment by kemzops** [comment]
السلام عليكم... في البداية حابب اوضح ان المشكلة تتعلق بـسيرفر الصوت الخاص بك وليس لها علاقة مباشرة بالتطبيق... ولكن أتوقع أن المشكلة تتعلق بصلاحيات الفلاتباك للتطبيق `Connection refused` اقترح استخدام اداة مثل `Flatsteal` وإعطاء صلاحية للتطبيق بالوصول الى سيرفر الصوت الخاص بجهازك `pulseaudio`

او تشغيل التطبيق ببارامتر `socket=pulseaudio`  مثلا !

`flatpak run org.altaqwaa.rn0x socket=pulseaudio`

بالرجوع الى الصلاحيات الموجودة [Flatpak Docs](https://docs.flatpak.org/de/latest/sandbox-permissions-reference.html)

**Comment by kemzops** [comment]
اظن مافي رد هقفل الـ Issue... لو المشكلة استمرت افتح Issue جديدة.
