### ISSUE TITLE
انهيار التطبيق فجاة

### ISSUE THREAD

**Issue by Ab-Mr** [rn0x/Altaqwaa-Islamic-Desktop-Application#51]
> عند فتح التطبيق وعمل اخفاء للنافذة ومحاولة اظهاره مرة أخرى 
يتعطل التطبيق 

،معلومات النظام

Name OS; Fedora Linux 38 (Workstation Edition)
Windowing system; Wayland
Kernel version ; Linux 6.5.7-200.fc38.x86_64
GNOME version; 44.5
 
؟ شغلت التطبيق من الطرفية

 ثبته من فلاتباك | Flatpak 

Error log

> [Altaqwaa-CLI] Altaqwaa For Linux.
[49:1031/005107.481559:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is egl, ANGLE is 
[Altaqwaa-CLI] Hidden & Minimized.
>
>[3:1031/005131.569767:ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@31: error 0: gtk_shell::get_gtk_surface already requested

>/app/bin/run.sh: line 8:     3 Trace/breakpoint trap   (core dumped) zypak-wrapper.sh /app/bin/altaqwaa "$@" --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations
>

**Comment by kemzops** [comment]
اولا حابب اعتذر لأني فعليا الي فترة مشغول ومافي وقت فراغ اكمل دعم المشروع ولكن بحاول افرغ وقت من فترة لفترة خصوصا للإصدار القادم...

المشكلة مش من التطبيق نفسه, المشكلة من `electron` وهو المسؤول عن كل العمليات الي بتصير من ناحية تعامله مع الـ`Display Server` وفي حالتك `Wayland`... وبالفعل `electron` تم تحديثه باصدار جديد لحل هاي المشكلة ولكن للأسف تحديثه يتطلب تحديث ملفات البناء الخاصة بالتطبيق واعادة نشره باصدار جديد , من هاي الناحية صراحة حاليا انا شغال على الاصدار الجديد `v4` من التطبيق وهيكون ان شاء الله بداية جديدة للتطبيق وكلشيء هيتم تحديثه لآخر الإصلاحات... بالوقت الحالي مافي أي حل من طرفي الى اذا بدك تحمل السورس كود وتحدث `electron` وتعمله `build بنفسك وتستخدمه.

**Comment by Ab-Mr** [comment]
شكرا على المعلومات كانت **قيمة** ، سأنظر في الأمر. **اشكرك**
