### ISSUE TITLE
القرآن يتوقف إذا غيرت مكاني في التطبيق والتطبيق لا يبقى في الخلفية kde plasma debian 12

### ISSUE THREAD

**Issue by Mouad-Ouazin** [rn0x/Altaqwaa-Islamic-Desktop-Application#52]

**Comment by Mouad-Ouazin** [comment]
والنوافد يجب ان تكون gtk يخصصها المستخدم كيف يشاء

**Comment by Mouad-Ouazin** [comment]
وشكرا على التطبيق المفتوح المصدر

**Comment by kemzops** [comment]
في الاصدار القادم `v4`, هتقدر تشغل القرآن بشكل منفصل عن التطبيق نفسه لانه حاليا لما تشغل القرآن وتغير مكانك بالتطبيق بيتم تحديث الصفحة كاملة مع مشغل القرآن... وبالنسبة لـ `GTK` حاليا مافي اي خطط لعمل التطبيق `Native`, بحيث التطبيق حاليا يشتغل على ويندوز ولينكس بنفس الشكل وبدون اطر عمل ومكاتب للنوافذ.
