### ISSUE TITLE
خلط في المحتوى

### ISSUE THREAD

**Issue by NasreddineLoukriz** [rn0x/Altaqwaa-Islamic-Desktop-Application#53]
في صفحة اسماء الله الحسنة يوجد خطأ تم خلط بين اسم الحليم وشرحه معى الصبور وشرحه سبحانه عزوجل
![Screenshot_20231214-200526_التقوى](https://github.com/Alsarmad/Altaqwaa-Islamic-Desktop-Application/assets/110660818/e07bcd96-0ee5-4a25-a9b6-979d178bfadb)
![Screenshot_20231214-200517_التقوى](https://github.com/Alsarmad/Altaqwaa-Islamic-Desktop-Application/assets/110660818/0c995128-caf4-46b7-8053-cf6950df0e21)

**Comment by rn0x** [comment]
شكرا لك على التنبيه تم تعديل الخطأ

https://github.com/Alsarmad/altaqwaa_android/releases/tag/v1.2.2
