### ISSUE TITLE
يمكنني بناء البرنامج على نظام تشغيل لينكس ؟

### ISSUE THREAD

**Issue by Al-fata-tayeb** [rn0x/Altaqwaa-Islamic-Desktop-Application#54]
أريد بناء برنامج الجميل هذا على نظام تشغيل debian و أرغب في الحصول على نسخة 86x من هذا برنامج لو سمحت و بارك الله فيكم

**Comment by kemzops** [comment]
https://github.com/Alsarmad/Altaqwaa-Islamic-Desktop-Application/discussions/55
