### ISSUE TITLE
Support MacOS

### ISSUE THREAD

**Issue by IslamAlorabI** [rn0x/Altaqwaa-Islamic-Desktop-Application#56]
Will there be a **MacOS** version in the future?

**Comment by kemzops** [comment]
@IslamAlOrabI for now its really hard for us to support macos in the official releases, but if you have MacOS you can build the application from source.

**Comment by IslamAlorabI** [comment]
@kemzops 
okay, I got you. I will try

**Comment by kemzops** [comment]
> @kemzops 
> okay, I got you. I will try 

if you want any help building it, check electron and electron-builder docs, if you still cant build it contact with me.
