### ISSUE TITLE
نقل المشروع لحسابك الشخصي بدون مناقشة مسبقة بشكل مفاجئ وغير متوقع

### ISSUE THREAD

**Issue by kemzops** [rn0x/Altaqwaa-Islamic-Desktop-Application#59]
أولاً، حابب أقول إني سعيد بالتقدم اللي وصلنا له في المشروع، ومتحمس جدًا لما هو قادم. لكن لاحظت مؤخرًا أن المشروع تم نقله لحسابك الشخصي، وكان شيء مفاجئ بالنسبة لي.

زي ما تعرف، كل واحد فينا قدم مساهمات كبيرة في التطوير. من فترة، اتفقنا على نقل المشروع لمنظمة جيت هب عشان يكون العمل المشترك أسهل وأكثر شفافية، واستمرينا في العمل بهذا الشكل لمدة سنة تقريبًا. حصلت مشاكل شخصية ما حبيت أدخلك فيها، وانقطعت عن المشروع لمدة نصف عام تقريبًا، ولم أرَ أي اهتمام منك تجاه المشروع خلال هذه الفترة.

لكن نقل المشروع لحسابك الشخصي بدون ما نتناقش فجأة حسيت إنه خطوة غريبة شوي، فحبيت أستفسر عن السبب ونتكلم بخصوص هذا الموضوع. أعتقد إننا نقدر نوصل لحل يخدم الجميع.

بانتظار رأيك، وشكرًا لتفهمك!

**Comment by rn0x** [comment]
أولاً, السلام عليكم ورحمة الله وبركاته
مرحبا بك اخي عزيز كيف حالك وكيف صحتك, أُقدِّر لك إهتمامك وحرصك على المشروع, مجهوداتك تشكر عليها ولاتنسى ابداً أنت وباقي المساهمين جميعاً جزاكم الله خير.

لا أعلم لما فتحت Issues بخصوص هذا الموضوع لو تواصلت معي عبر تيليجرام او الإيميل لكان افضل.
عموماً, أود ان اوضح أن نقل المشروع لحسابي الشخصي لم يكن بهدف إستبعاد أي مساهمات أو تجاهل أي جهود بُذلت, كما تعلم ان المشروع كان على حسابي الشخصي وقمت بنقله الى المنظمة بناءً على طلبك (أيضا قمت بنقل العديد من المشاريع الأخرى, على امل ان يكون هناك من يساهم ويطور هذه المشاريع),  وتكلفت مادياً لاكن مع الأسف لم يكن هناك مساهمين كفاية وخصوصاً في الفترة الاخير (خلال الثمانية أشهر السابقة) لم يكن هناك اي تفاعل أو مساهمات من اعضاء المنظمة, حتى انت اخي الكريم مثل ماذكرت انقطعت لفترة طويلة ولم يكن بيننا أية تواصل, لذلك شعرت ان الأفضل لإستمرآر المشروع ان انقله الى حسابي الشخصي, **ونقل المشروع الى حسابي ليست إشكال لمن أراد ان يساهم في المشروع, كلها ثلاث خطوات للمساهمة.**



> لمدة نصف عام تقريبًا، ولم أرَ أي اهتمام منك تجاه المشروع خلال هذه الفترة.

كيف لم ترى أي اهتمام ؟ أنا اغلب وقتي رايح في تطوير هذه المشاريع (التقوى) او المشاريع المرتبطة بها.
وحالياً شغال على تطبيق  الأندرويد وإحتمال ايضاً استعمل نفس الواجهة لتطبيق سطح المكتب.
 
 
<img width="384" alt="brave_qPEGnjlYqw" src="https://github.com/user-attachments/assets/f1a7a378-e534-4693-9724-27c4f5b6a68c">

<img width="195" alt="brave_GEiZjnEBQJ" src="https://github.com/user-attachments/assets/22d3d01f-f5b5-4892-8520-c91ed2fe5e95">

<img width="195" alt="brave_Ce6kQoRYDE" src="https://github.com/user-attachments/assets/58647127-7fd3-466e-a49c-befbfffb583c">

**Comment by rn0x** [comment]
<img width="384" alt="brave_Yc3bjE92KR" src="https://github.com/user-attachments/assets/4fd76d09-9edc-468f-8c70-a363a470b250">


![icon-192](https://github.com/user-attachments/assets/f0ab0ada-7cca-4718-9026-db18574e334f)

**Comment by kemzops** [comment]
بإذن الله سأتواصل معك عن طريق التليجرام بأقرب وقت ، شكرا على ردك. @rn0x
